### ISSUE TITLE
How to add 3rd party SDK?

### ISSUE THREAD

**Issue by dheerajbred** [karnadii/ironsource#2]
This isn't an issue. I have a question

How to add 3rd party SDK?
![image](https://user-images.githubusercontent.com/46578244/62823741-f83f1500-bbb1-11e9-8503-b7dc75c9065f.png)

Where to add these? Should I add these to my app-level build.gradle or ironsource-module build.gradle?

**Comment by karnadii** [comment]
your app level. https://github.com/karnadii/ironsource/blob/master/example/android/app/build.gradle.

**Comment by karnadii** [comment]
don't add ironsource sdk anymore, just add the facebook and Charboost sdk.
