### ISSUE TITLE
Poor design interface

### ISSUE THREAD

**Issue by lau1944** [karnadii/ironsource#7]
Using this api is just pure pain. I have to go through your whole source code to find out a bug I am facing, and I am in pain reading your code. Anyway, it's better to make my own plugin

**Comment by karnadii** [comment]
![IMG_20210613_111008.jpg](https://user-images.githubusercontent.com/18657277/121795133-f45dfd00-cc37-11eb-8482-163138a6a6eb.jpg)

Can't you read?  I have zero knowledge of java, what I did was copy and paste someone else code. If you can make a better plugin, please provide a better plugin for the community. When I was writing this plugin there are no ironsource plugin, at that time it was better than nothing.

**Comment by lau1944** [comment]
> ![IMG_20210613_111008.jpg](https://user-images.githubusercontent.com/18657277/121795133-f45dfd00-cc37-11eb-8482-163138a6a6eb.jpg)
> 
> Can't you read? I have zero knowledge of java, what I did was copy and paste someone else code. If you can make a better plugin, please provide a better plugin for the community. When I was writing this plugin there are no ironsource plugin, at that time it was better than nothing.

It is not related to java code, it is on dart interface.
ex: I know it's copy, paste, but you are using this plugin right? 
Don't you think It is too boilerplate code? 
 if I want to init the plugin, the Listener arguement is  'required'  and I have to implement 22 callback in my view.

**Comment by karnadii** [comment]
Oh, I was planning to use this plugin, but ironsource app require approval to show ads. And my apps is not eligible. so in the end this plugin was useless and I don't use this plugin I am using unity ads now. 

Last time I check I have to email them. (ironsource) to show ads in my apps. Is your app is the same?
